/**
 * Shared types for the Interesting Finds pipeline.
 *
 * This module is the single contract between lanes: ingest (W2), the crawler
 * (W4), scoring (W5), the digest (W6) and the site page (W7) all speak these
 * shapes. W3 owns the file; other lanes propose changes through the
 * coordinator. Every type here mirrors a table in supabase/migrations, and the
 * migration is the authority -- if the two disagree, the SQL is right.
 *
 * Convention: `Row` types are what the database hands back (timestamps are ISO
 * strings, as PostgREST returns them). `New*` types are what a writer supplies,
 * omitting anything the database fills in.
 */

/** ISO 8601 timestamp string, as PostgREST serialises TIMESTAMPTZ. */
export type Timestamp = string;

/* ========================================================================== */
/* sources                                                                     */
/* ========================================================================== */

/**
 * How we authenticate to a source. `session_cookie` is credential replay and
 * is expected to expire -- see DECISIONS D3.
 */
export type SourceAuthKind =
  | 'none'
  | 'public_api'
  | 'api_key'
  | 'oauth'
  | 'session_cookie';

/**
 * Computed source status. The point of `down` is that it is distinguishable
 * from "found nothing today": an expired Peerlist cookie must be reported, not
 * absorbed into an empty result.
 */
export type SourceStatus = 'ok' | 'stale' | 'down' | 'disabled';

/** A row of `finds_sources`. Private: readable only with the service role. */
export interface SourceRow {
  id: string;
  slug: string;
  display_name: string;
  homepage_url: string;
  enabled: boolean;
  auth_kind: SourceAuthKind;
  /** Known expiry of the credential. `null` means unknown, never means valid. */
  credential_expires_at: Timestamp | null;
  last_attempt_at: Timestamp | null;
  last_success_at: Timestamp | null;
  /** Verbatim failure reason. Never a credential. */
  last_error: string | null;
  last_error_at: Timestamp | null;
  consecutive_failures: number;
  /** No success inside this window makes the source `stale`. */
  staleness_budget_hours: number;
  created_at: Timestamp;
  updated_at: Timestamp;
}

export type NewSource = Pick<SourceRow, 'slug' | 'display_name' | 'homepage_url'> &
  Partial<Pick<SourceRow, 'enabled' | 'auth_kind' | 'credential_expires_at' | 'staleness_budget_hours'>>;

/** A row of the `finds_source_health` view. */
export interface SourceHealthRow {
  id: string;
  slug: string;
  display_name: string;
  status: SourceStatus;
  last_success_at: Timestamp | null;
  last_attempt_at: Timestamp | null;
  last_error: string | null;
  last_error_at: Timestamp | null;
  consecutive_failures: number;
  credential_expires_at: Timestamp | null;
}

/* ========================================================================== */
/* candidates                                                                  */
/* ========================================================================== */

/**
 * Work-queue marker on a candidate. Not a second copy of the truth -- what
 * actually happened to a candidate is the rows in the crawl-verdict, evidence
 * and verdict tables. This exists so a cron run can find its next batch.
 */
export type CandidateStatus =
  | 'new'
  | 'gate_blocked'
  /** Fetch was allowed, but ai-input is reserved, so C1-C4 cannot be evaluated
   *  at all (R2 §3.2). A non-evaluation, never a low score -- inventing a
   *  verdict for it is what D6 forbids. */
  | 'not_evaluable'
  | 'crawled'
  | 'scored'
  | 'digested'
  | 'published'
  | 'rejected';

/**
 * What `product_url` actually points at.
 *
 * `dedicated` is the project's own site, so its pages are the project's words.
 * `shared_host` is a tenant under a path on someone else's host --
 * github.com/owner/repo, a Substack, an App Store listing -- where the
 * surrounding pages belong to the host, not the project.
 *
 * The distinction is D23: a project's README claim was recorded as CONTRADICTED
 * by a sentence from github.com/pricing, which under D7 disqualified it. Treat
 * `shared_host` evidence as thin and scoped to the path prefix.
 *
 * `unknown` means not classified. It is never an endorsement -- do not fall
 * back to treating it as `dedicated`, which is the assumption D23 punished.
 */
export type ProductUrlKind = 'dedicated' | 'shared_host' | 'unknown';

/** A row of `finds_candidates`. Private. */
export interface CandidateRow {
  id: string;
  /** The product website as first reported, verbatim. */
  product_url: string;
  /**
   * The cross-source dedupe key, GENERATED by the database from product_url
   * via `finds_normalize_url()`. Never write this -- Postgres rejects it.
   */
  canonical_url: string;
  name: string;
  tagline: string | null;
  /** Defaults to 'unknown' in the database; never assume 'dedicated'. */
  product_url_kind: ProductUrlKind;
  first_seen_at: Timestamp;
  last_seen_at: Timestamp;
  status: CandidateStatus;
  created_at: Timestamp;
  updated_at: Timestamp;
}

/**
 * What a connector supplies. `canonical_url` is absent on purpose: it is a
 * generated column, so normalisation cannot be forgotten or disagreed about.
 * Upsert with `ON CONFLICT (canonical_url) DO UPDATE SET last_seen_at = NOW()`.
 */
/**
 * Required here even though the column has a database default, so a connector
 * that has not classified the URL has to say `'unknown'` out loud rather than
 * silently inheriting it. The default exists to keep already-deployed writers
 * working, not as a shape anyone should target.
 */
export type NewCandidate = Pick<
  CandidateRow,
  'product_url' | 'name' | 'product_url_kind'
> &
  Partial<Pick<CandidateRow, 'tagline'>>;

/** A row of `finds_candidate_sightings`: one platform listing. Private. */
export interface CandidateSightingRow {
  id: string;
  candidate_id: string;
  source_id: string;
  /** The platform's own id. UNIQUE with source_id, so re-pulling is idempotent. */
  external_id: string;
  /** The listing page ON the platform -- what W9 comments on, not the product site. */
  source_url: string;
  title: string | null;
  author_handle: string | null;
  posted_at: Timestamp | null;
  /** Verbatim source payload for this item. Never edited. */
  raw: Record<string, unknown>;
  seen_at: Timestamp;
}

export type NewCandidateSighting = Pick<
  CandidateSightingRow,
  'candidate_id' | 'source_id' | 'external_id' | 'source_url'
> &
  Partial<Pick<CandidateSightingRow, 'title' | 'author_handle' | 'posted_at' | 'raw'>>;

/* ========================================================================== */
/* evidence                                                                    */
/* ========================================================================== */

/** What a fetched page is to us, so scoring can ask for the pricing page. */
export type EvidencePageRole =
  | 'homepage'
  | 'pricing'
  | 'docs'
  | 'api'
  | 'mcp'
  | 'changelog'
  | 'about'
  | 'blog'
  | 'repo'
  | 'robots_txt'
  | 'llms_txt'
  | 'other';

/** Something the page asserts. The left-hand side of the C1 diff. */
export interface EvidenceClaim {
  text: string;
  /** Where on the page it was found -- selector, heading, or section. */
  locator?: string;
}

/** A verbatim excerpt. Quoted, never paraphrased, so a score is auditable. */
export interface EvidenceQuote {
  text: string;
  locator?: string;
}

/** Measured behaviour rather than text: an endpoint responded, a schema parsed. */
export interface EvidenceObservation {
  kind: string;
  detail?: string;
  value?: string | number | boolean | null;
}

/**
 * A row of `finds_evidence`. Private, immutable and append-only -- a trigger
 * refuses UPDATE, DELETE and TRUNCATE for every caller, service role included,
 * because RLS cannot stop a role that bypasses RLS. Re-crawling appends a new
 * generation under a fresh `crawl_run_id`; it never overwrites.
 */
export interface EvidenceRow {
  id: string;
  candidate_id: string;
  /**
   * The gate decision that permitted this fetch. The FK is composite on
   * (id, allowed), so evidence from a DENIED verdict cannot be inserted at all.
   */
  crawl_verdict_id: string;
  /** Groups one crawl pass. Verdicts record which generation they scored. */
  crawl_run_id: string;
  url: string;
  page_role: EvidencePageRole;
  /** A 404 on /docs is evidence, not a missing row. */
  http_status: number | null;
  content_type: string | null;
  content_sha256: string | null;
  fetched_at: Timestamp;
  claims: EvidenceClaim[];
  quotes: EvidenceQuote[];
  observations: EvidenceObservation[];
  created_at: Timestamp;
}

export type NewEvidence = Pick<
  EvidenceRow,
  'candidate_id' | 'crawl_verdict_id' | 'crawl_run_id' | 'url' | 'page_role'
> &
  Partial<
    Pick<
      EvidenceRow,
      'http_status' | 'content_type' | 'content_sha256' | 'fetched_at' | 'claims' | 'quotes' | 'observations'
    >
  >;

/* ========================================================================== */
/* verdicts                                                                    */
/* ========================================================================== */

/**
 * The four criteria.
 *   C1 what is advertised is actually true
 *   C2 solves a rare problem
 *   C3 usable by any person
 *   C4 agentic / MCP friendly
 */
export type Criterion = 'C1' | 'C2' | 'C3' | 'C4';

/**
 * How well the evidence supports the criterion. The scale is about evidential
 * support rather than about the product, which is what keeps one scale
 * meaningful across all four criteria.
 *   0 the evidence contradicts it
 *   1 no evidence either way
 *   2 partially supported
 *   3 clearly supported by quoted or measured evidence
 */
export type VerdictScore = 0 | 1 | 2 | 3;

/**
 * A row of `finds_verdicts`. Private.
 *
 * Insert one of these WITHOUT also inserting `finds_verdict_evidence` rows in
 * the same transaction and the COMMIT aborts: a deferred constraint trigger
 * enforces DECISIONS D7. `rationale` does not satisfy it -- prose is
 * supplementary to the citations, never a substitute.
 */
export interface VerdictRow {
  id: string;
  candidate_id: string;
  /** Which crawl generation was scored. Matches the cited rows' crawl_run_id. */
  evidence_run_id: string;
  criterion: Criterion;
  score: VerdictScore;
  rationale: string;
  /** Model id, or 'human'. Says WHO scored it, not under which rules. */
  scored_by: string;
  /**
   * The scoring rubric revision that produced this score. A bare 0-3 stops
   * being readable the moment the rules move underneath it, which is the same
   * reasoning that put rubric_version on CrawlVerdictRow.
   */
  rubric_version: string;
  created_at: Timestamp;
  updated_at: Timestamp;
}

export type NewVerdict = Pick<
  VerdictRow,
  | 'candidate_id'
  | 'evidence_run_id'
  | 'criterion'
  | 'score'
  | 'rationale'
  | 'scored_by'
  | 'rubric_version'
>;

/**
 * Contradicting evidence is a citation too: a score of 0 must point at it.
 *
 * `inconclusive` is what a score of 1 cites -- evidence we looked at that
 * settled nothing. Without it the only way to record a 1 was to mislabel its
 * citations, which would make D7's audit trail lie in exactly the cases where
 * nothing was proven, and `contradicts` would accuse a real company of
 * something their own page does not show.
 */
export type CitationStance = 'supports' | 'contradicts' | 'inconclusive';

/**
 * A row of `finds_verdict_evidence`. `candidate_id` and `evidence_run_id` are
 * both redundant on purpose -- they are what let the foreign keys be composite,
 * so citing another product's evidence, or evidence from a crawl generation
 * this score did not read, is a foreign-key violation rather than a review
 * catch.
 *
 * The run matters because evidence is append-only: several generations of the
 * same page coexist, and citing across them would reintroduce exactly the drift
 * immutability buys. A re-crawl that fixed a 404 would otherwise let a stale
 * score keep citing the 404.
 */
export interface VerdictEvidenceRow {
  verdict_id: string;
  evidence_id: string;
  candidate_id: string;
  /** Must equal the verdict's `evidence_run_id` and the evidence's `crawl_run_id`. */
  evidence_run_id: string;
  stance: CitationStance;
  created_at: Timestamp;
}

export type NewVerdictEvidence = Pick<
  VerdictEvidenceRow,
  'verdict_id' | 'evidence_id' | 'candidate_id' | 'evidence_run_id'
> &
  Partial<Pick<VerdictEvidenceRow, 'stance'>>;

/* ========================================================================== */
/* published finds -- the only public shape                                    */
/* ========================================================================== */

/**
 * One citation shown on the public page: the evidence behind a score, copied
 * out of `finds_evidence` at publish time rather than joined, because the
 * evidence table is private and must stay that way.
 */
export interface PublishedCitation {
  criterion: Criterion;
  url: string;
  /** Verbatim excerpt. Absent when the citation is a measured behaviour. */
  quote?: string;
  stance: CitationStance;
}

/**
 * A row of `finds_published` -- the ONLY anon-readable table in this
 * initiative (DECISIONS D8). W7 renders from this and nothing else.
 *
 * It is a snapshot, not a view. The browser holds the anon key, so anything
 * anon can select is public whether or not a page renders it; a join to
 * candidates, evidence and verdicts would either leak the private pipeline or
 * need a view that reads past RLS. It is also the honest editorial model: a
 * published find is what Nikhil approved on the day he approved it, and a later
 * re-crawl must not silently rewrite a page carrying his name.
 *
 * Rows with `published_at` null or in the future are invisible to anon, so a
 * draft cannot be read by asking for it directly.
 */
export interface PublishedFindRow {
  id: string;
  candidate_id: string;
  /** URL segment on the site: /interesting-finds/<slug> */
  slug: string;
  name: string;
  tagline: string | null;
  product_url: string;
  /** Platforms it was seen on. Appearing on three at once is part of the story. */
  source_labels: string[];
  found_at: Timestamp;
  published_at: Timestamp | null;
  /** C1: what is advertised is actually true. Same 0-3 scale as VerdictScore. */
  score_claim_verified: VerdictScore;
  /** C2: solves a rare problem. */
  score_rare_problem: VerdictScore;
  /** C3: usable by any person. */
  score_anyone_can_use: VerdictScore;
  /** C4: agentic / MCP friendly. */
  score_agentic_friendly: VerdictScore;
  /** Non-empty by CHECK: going public does not suspend D7. */
  citations: PublishedCitation[];
  /** Nikhil's own words, or null. Per D4 nothing generated goes here. */
  why_interesting: string | null;
  created_at: Timestamp;
  updated_at: Timestamp;
}

/**
 * What W7 actually receives. `published_at` is non-null for every row the anon
 * key can see, so the page never has to handle a draft.
 */
export type VisiblePublishedFind = Omit<PublishedFindRow, 'published_at'> & {
  published_at: Timestamp;
};

/* ========================================================================== */
/* digests                                                                     */
/* ========================================================================== */

/**
 * A digest cannot claim a delivery it did not get: `sent` requires `sent_at`
 * and `failed` requires `error`, both by CHECK. Per D2 and D6, W6 may not fake
 * a successful send.
 */
export type DigestStatus = 'pending' | 'sent' | 'failed';

/** A row of `finds_digests`. Private. */
export interface DigestRow {
  id: string;
  subject: string;
  recipient: string;
  status: DigestStatus;
  sent_at: Timestamp | null;
  /** Whatever the transport returned. Evidence a send really happened. */
  provider_message_id: string | null;
  /** Verbatim failure. Never a credential -- D2 forbids echoing the app password. */
  error: string | null;
  created_at: Timestamp;
  updated_at: Timestamp;
}

export type NewDigest = Pick<DigestRow, 'subject' | 'recipient'>;

/**
 * A row of `finds_digest_items`.
 *
 * `digest_status` is a trigger-maintained mirror of the parent digest's status
 * and must never be written by hand. It exists so "a candidate may appear in at
 * most one SENT digest" can be a partial unique index, which Postgres cannot
 * build across a join. The consequence that matters: a failed send does not
 * consume its candidates, so finds Nikhil never received are not lost.
 */
export interface DigestItemRow {
  digest_id: string;
  candidate_id: string;
  /** Order in the email, so the digest can be reconstructed exactly. */
  position: number;
  digest_status: DigestStatus;
  created_at: Timestamp;
}

export type NewDigestItem = Pick<DigestItemRow, 'digest_id' | 'candidate_id' | 'position'>;

/**
 * A row of the `finds_undigested_candidates` view: candidates not yet in a
 * successfully sent digest. Select from this rather than writing a NOT EXISTS
 * clause, so the never-twice rule lives in one place.
 */
export type UndigestedCandidateRow = CandidateRow;

/* ========================================================================== */
/* crawl verdicts -- the permission gate (R2-permission-rubric v1.1 §6)        */
/* ========================================================================== */

/**
 * R2 §6.1. The split is not cosmetic: a CHECK ties `allowed` to it, so a
 * verdict claiming it was allowed for a denying reason is not representable.
 */
export type GateAllowReason =
  | 'robots_exact_group'
  | 'robots_allow'
  | 'robots_wildcard_allow'
  | 'robots_no_rules'
  | 'robots_absent'
  | 'robots_soft_404'
  | 'robots_redirect_loop';

export type GateDenyReason =
  | 'manual_denylist'
  | 'url_out_of_scope'
  | 'robots_disallow'
  | 'robots_wildcard_disallow'
  | 'ai_block_inferred'
  | 'robots_forbidden'
  | 'robots_rate_limited'
  | 'robots_server_error'
  | 'robots_unreachable'
  | 'robots_bad_success'
  | 'origin_blocked_us'
  | 'origin_rate_limited'
  | 'bot_challenge'
  | 'unhandled_case';

export type GateReasonCode = GateAllowReason | GateDenyReason;

/** R2 §6.2. USE-axis signals never appear here -- they never decide access. */
export type GateDecidingSignal =
  | 'MANUAL_DENYLIST'
  | 'URL_POLICY'
  | 'ROBOTS_TXT'
  | 'AI_BLOCK_INFERENCE'
  | 'HTTP_STATUS'
  | 'BOT_CHALLENGE'
  | 'RATE_LIMIT'
  | 'CACHED_VERDICT'
  | 'UNHANDLED';

/** R2 §3.2. Start permissive, let every signal subtract; `train` is always false. */
export interface GateUseRights {
  llm_ingest: boolean;
  publish_excerpt: boolean;
  publish_link: boolean;
  follow_links: boolean;
  store_raw_body: boolean;
  /** Constant false. Not configurable. */
  train: false;
  max_snippet_chars: number | null;
  reserved_by: Array<{
    signal: string;
    directive: string;
    source_url: string;
    restricts: string[];
  }>;
}

/** R2 §5.3. What we will do if allowed. */
export interface GateCrawlBudget {
  delay_ms: number;
  delay_source: 'CRAWL_DELAY' | 'DEFAULT';
  page_cap: number;
  depth_cap: number;
  wall_clock_ms: number;
}

/**
 * A row of `finds_crawl_verdicts`. Private.
 *
 * One row per URL ASKED ABOUT, not per page fetched: a DENY produces a row too,
 * and those rows are the proof we behaved. Never deleted (R2 §6.3), and the
 * decision is final -- only `expires_at` and `revalidated_at` may change, for
 * the 304 revalidation of R2 §7. A new decision is a new row.
 */
export interface CrawlVerdictRow {
  id: string;
  /** The rubric revision that decided this. A verdict is only readable against it. */
  rubric_version: string;
  gate_version: string;
  candidate_id: string;
  url: string;
  /** scheme://host[:port] -- the cache key per R2 §7. NOT the registrable domain. */
  authority: string;
  registrable_domain: string;
  allowed: boolean;
  reason_code: GateReasonCode;
  reason_detail: string;
  deciding_signal: GateDecidingSignal;
  /** The literal line from their robots.txt, verbatim. The primary exhibit. */
  deciding_rule: string | null;
  deciding_group: string | null;
  precedence_rule: string | null;
  use_rights: GateUseRights | Record<string, never>;
  crawl_budget: GateCrawlBudget | Record<string, never>;
  robots: Record<string, unknown>;
  decided_at: Timestamp;
  /** Null only for `manual_denylist`: a human decided, only a human undoes it. */
  expires_at: Timestamp | null;
  revalidated_at: Timestamp | null;
  created_at: Timestamp;
}

export type NewCrawlVerdict = Pick<
  CrawlVerdictRow,
  | 'rubric_version'
  | 'gate_version'
  | 'candidate_id'
  | 'url'
  | 'authority'
  | 'registrable_domain'
  | 'allowed'
  | 'reason_code'
  | 'reason_detail'
  | 'deciding_signal'
  | 'expires_at'
> &
  Partial<
    Pick<
      CrawlVerdictRow,
      'deciding_rule' | 'deciding_group' | 'precedence_rule' | 'use_rights' | 'crawl_budget' | 'robots'
    >
  >;

/**
 * A row of `finds_crawl_evidence`: everything fetched to reach one decision.
 * Append-only. A CHECK refuses any header bag containing Cookie or
 * Authorization (R2 §6.3) -- we never send one, and the schema asserts it.
 */
export interface CrawlEvidenceRow {
  id: string;
  verdict_id: string;
  url: string;
  method: string;
  /** Who we said we were. Half of answering "why did you crawl me". */
  request_user_agent: string;
  request_headers: Record<string, string | null>;
  http_status: number | null;
  /** An allowlisted subset, never the whole bag. */
  response_headers: Record<string, string | null>;
  content_length: number | null;
  sha256: string | null;
  /** robots.txt verbatim, capped at 512000 bytes. */
  body_excerpt: string | null;
  fetched_at: Timestamp;
  elapsed_ms: number | null;
  remote_ip: string | null;
  created_at: Timestamp;
}

export type NewCrawlEvidence = Pick<
  CrawlEvidenceRow,
  'verdict_id' | 'url' | 'request_user_agent' | 'fetched_at'
> &
  Partial<
    Pick<
      CrawlEvidenceRow,
      | 'method'
      | 'request_headers'
      | 'http_status'
      | 'response_headers'
      | 'content_length'
      | 'sha256'
      | 'body_excerpt'
      | 'elapsed_ms'
      | 'remote_ip'
    >
  >;

/* ========================================================================== */
/* finds_write_verdict -- the D7/D17 transaction bridge                        */
/* ========================================================================== */

/**
 * One citation as the RPC payload carries it. `stance` may be omitted and the
 * column default ('supports') applies.
 */
export interface WriteVerdictCitation {
  evidence_id: string;
  stance?: CitationStance;
}

/** One verdict as the RPC payload carries it. `citations` must be non-empty. */
export interface WriteVerdictPayload {
  criterion: Criterion;
  score: VerdictScore;
  rationale: string;
  scored_by: string;
  citations: WriteVerdictCitation[];
}

/**
 * Arguments for `supabase.rpc('finds_write_verdict', args)`.
 *
 * Why this exists rather than two inserts: D7's citation check is a
 * DEFERRABLE INITIALLY DEFERRED constraint trigger that fires at COMMIT, and
 * PostgREST gives one transaction per HTTP request (D17). Inserting the verdict
 * and then its citations commits the verdict alone, the trigger fires against
 * it uncited, and the transaction aborts -- correctly. One function call is one
 * transaction, so it can satisfy the constraint that two calls cannot.
 *
 * Every guarantee still holds at COMMIT: the deferred trigger runs, and both
 * `candidate_id` and `evidence_run_id` for each citation are taken from the
 * arguments rather than from the payload -- so the composite FKs make citing
 * another product's evidence, or evidence from a generation this score did not
 * read, impossible even if the payload asks for it.
 *
 * Service role only -- EXECUTE is revoked from anon and authenticated, because
 * PostgREST exposes every function as an endpoint and this one writes.
 */
export interface WriteVerdictArgs {
  p_candidate_id: string;
  p_evidence_run_id: string;
  /** Required. A defaulted version would stamp a rubric onto scores it did not produce. */
  p_rubric_version: string;
  p_verdicts: WriteVerdictPayload[];
}

/* ========================================================================== */
/* approvals -- the one thing that may cause a public page to appear (D29)     */
/* ========================================================================== */

/**
 * D9: Telegram is the control surface and the digest email is read-only. One
 * member on purpose, matching W11's `ApprovalChannel` -- an approval arriving
 * by any other route is not representable, in the type or in the CHECK.
 */
export type ApprovalChannel = 'telegram';

/**
 * A row of `finds_approvals`. Private, service-role only, and append-only: an
 * approval is a receipt for something a person said at a moment, and editing
 * one would rewrite the record of consent that a public page about someone
 * else's product rests on.
 *
 * A superset of W11's `FindApproval`, so a row can be handed straight to
 * `assertApprovedByNikhil()`. That check must keep running: this table is a
 * wider surface than a file, and the publish path should not trust that the
 * writer validated `chat_id`.
 *
 * AN APPROVAL ENABLES A PUBLISH; IT NEVER TRIGGERS ONE. Publishing is not a
 * scheduled stage and must not be called from `finds/run/**`. There is
 * deliberately no view listing approved-but-unpublished finds -- that query is
 * the missing ingredient for a cron that would turn a missed rejection into a
 * live page, so a publisher writes it by hand, naming the find.
 */
export interface ApprovalRow {
  id: string;
  candidate_id: string;
  /**
   * The verdict generation he actually saw. An approval floating free of a
   * generation would let a later re-score publish evidence he never read.
   * A composite FK makes approving an unscored generation impossible.
   */
  evidence_run_id: string;
  /** Pinned to 'C1'. Exists only to make that FK composite; never set it yourself. */
  approved_criterion: 'C1';
  channel: ApprovalChannel;
  /** Re-check this against TELEGRAM_CHAT_ID at read time. Always. */
  chat_id: string;
  /** Bot API message id of his answer -- the receipt. */
  message_id: number;
  /** Provenance only. `(chat_id, message_id)` is the replay key, not this. */
  telegram_update_id: number | null;
  /** Verbatim. Non-empty by CHECK: silence is not consent. */
  answer: string;
  /** Prose he wrote, or null. Per D4 nothing generated is ever written here. */
  why_interesting: string | null;
  answered_at: Timestamp;
  created_at: Timestamp;
}

/**
 * What W8's poller inserts.
 *
 * Write it with `ON CONFLICT (chat_id, message_id) DO NOTHING`. That unique key
 * absorbs a re-read of the same update after a runner restart, which is
 * precisely why the getUpdates offset does not also need to be durable for
 * publishing to be correct.
 */
export type NewApproval = Pick<
  ApprovalRow,
  'candidate_id' | 'evidence_run_id' | 'chat_id' | 'message_id' | 'answer' | 'answered_at'
> &
  Partial<Pick<ApprovalRow, 'channel' | 'telegram_update_id' | 'why_interesting'>>;

/* ========================================================================== */
/* HITL pending questions -- one store for asker and poller (D34)             */
/* ========================================================================== */

export type HitlPendingKind = 'plain' | 'approval';

/** One inline-keyboard button. */
export interface HitlPendingOption {
  label: string;
}

/**
 * A row of `finds_hitl_pending`. Private, service-role only.
 *
 * Unlike `ApprovalRow` and `EvidenceRow` this is MUTABLE and DELETABLE, and the
 * difference is principled rather than convenient: append-only guards a record
 * something else relies on as evidence. Nothing relies on a pending question
 * once it is answered -- the approval row is what W11 reads, and D29 settled
 * that rejections leave no trace. A resolved question is simply gone, so
 * "is there a row?" is the open/closed test and no reader has to remember a
 * `resolved_at` filter.
 */
export interface HitlPendingRow {
  /**
   * Caller-generated, with no database default. It is embedded in Telegram's
   * callback_data (`q:<id>:<idx>`) before the row exists, so a server-generated
   * id would produce a row that no tap could ever match.
   */
  id: string;
  chat_id: string;
  /** Bot API message id of the ask. A per-chat counter, hence unique with chat_id. */
  sent_message_id: number;
  prompt: string;
  context: string | null;
  /** NULL for a free-text-only ask. Required when `kind` is 'approval'. */
  options: HitlPendingOption[] | null;
  kind: HitlPendingKind;
  approval_candidate_id: string | null;
  approval_evidence_run_id: string | null;
  /** Pinned to 'C1'. Makes the FK composite; never set it yourself. */
  approval_criterion: 'C1' | null;
  /** Which option approves. Bounded against `options` by CHECK. */
  approve_option_index: number | null;
  /**
   * D32: free text is captured here, never acted on. Only an explicit tap
   * approves. Becomes `finds_approvals.why_interesting` if a later tap
   * approves. His prose verbatim -- per D4 nothing generated goes here.
   */
  draft_note: string | null;
  created_at: Timestamp;
}

/**
 * What the ask inserts. `id` is required because the caller minted it for the
 * callback_data. An 'approval' ask must supply the whole approval payload and
 * non-empty `options`; a half-filled one is refused by CHECK, and one naming an
 * unscored generation is a foreign-key violation.
 */
export type NewHitlPending = Pick<
  HitlPendingRow,
  'id' | 'chat_id' | 'sent_message_id' | 'prompt'
> &
  Partial<
    Pick<
      HitlPendingRow,
      | 'context'
      | 'options'
      | 'kind'
      | 'approval_candidate_id'
      | 'approval_evidence_run_id'
      | 'approval_criterion'
      | 'approve_option_index'
    >
  >;
