/**
 * Shared types for the Interesting Finds pipeline.
 *
 * This module is the single contract between lanes: ingest (W2), the crawler
 * (W4), scoring (W5), the digest (W6) and the site page (W7) all speak these
 * shapes. W3 owns the file; other lanes propose changes through the
 * coordinator. Every type here mirrors a table in supabase/migrations, and the
 * migration is the authority -- if the two disagree, the SQL is right.
 *
 * Convention: `Row` types are what the database hands back (timestamps are ISO
 * strings, as PostgREST returns them). `New*` types are what a writer supplies,
 * omitting anything the database fills in.
 */

/** ISO 8601 timestamp string, as PostgREST serialises TIMESTAMPTZ. */
export type Timestamp = string;

/* ========================================================================== */
/* sources                                                                     */
/* ========================================================================== */

/**
 * How we authenticate to a source. `session_cookie` is credential replay and
 * is expected to expire -- see DECISIONS D3.
 */
export type SourceAuthKind =
  | 'none'
  | 'public_api'
  | 'api_key'
  | 'oauth'
  | 'session_cookie';

/**
 * Computed source status. The point of `down` is that it is distinguishable
 * from "found nothing today": an expired Peerlist cookie must be reported, not
 * absorbed into an empty result.
 */
export type SourceStatus = 'ok' | 'stale' | 'down' | 'disabled';

/** A row of `finds_sources`. Private: readable only with the service role. */
export interface SourceRow {
  id: string;
  slug: string;
  display_name: string;
  homepage_url: string;
  enabled: boolean;
  auth_kind: SourceAuthKind;
  /** Known expiry of the credential. `null` means unknown, never means valid. */
  credential_expires_at: Timestamp | null;
  last_attempt_at: Timestamp | null;
  last_success_at: Timestamp | null;
  /** Verbatim failure reason. Never a credential. */
  last_error: string | null;
  last_error_at: Timestamp | null;
  consecutive_failures: number;
  /** No success inside this window makes the source `stale`. */
  staleness_budget_hours: number;
  created_at: Timestamp;
  updated_at: Timestamp;
}

export type NewSource = Pick<SourceRow, 'slug' | 'display_name' | 'homepage_url'> &
  Partial<Pick<SourceRow, 'enabled' | 'auth_kind' | 'credential_expires_at' | 'staleness_budget_hours'>>;

/** A row of the `finds_source_health` view. */
export interface SourceHealthRow {
  id: string;
  slug: string;
  display_name: string;
  status: SourceStatus;
  last_success_at: Timestamp | null;
  last_attempt_at: Timestamp | null;
  last_error: string | null;
  last_error_at: Timestamp | null;
  consecutive_failures: number;
  credential_expires_at: Timestamp | null;
}

/* ========================================================================== */
/* candidates                                                                  */
/* ========================================================================== */

/**
 * Work-queue marker on a candidate. Not a second copy of the truth -- what
 * actually happened to a candidate is the rows in the crawl-verdict, evidence
 * and verdict tables. This exists so a cron run can find its next batch.
 */
export type CandidateStatus =
  | 'new'
  | 'gate_blocked'
  | 'crawled'
  | 'scored'
  | 'digested'
  | 'published'
  | 'rejected';

/** A row of `finds_candidates`. Private. */
export interface CandidateRow {
  id: string;
  /** The product website as first reported, verbatim. */
  product_url: string;
  /**
   * The cross-source dedupe key, GENERATED by the database from product_url
   * via `finds_normalize_url()`. Never write this -- Postgres rejects it.
   */
  canonical_url: string;
  name: string;
  tagline: string | null;
  first_seen_at: Timestamp;
  last_seen_at: Timestamp;
  status: CandidateStatus;
  created_at: Timestamp;
  updated_at: Timestamp;
}

/**
 * What a connector supplies. `canonical_url` is absent on purpose: it is a
 * generated column, so normalisation cannot be forgotten or disagreed about.
 * Upsert with `ON CONFLICT (canonical_url) DO UPDATE SET last_seen_at = NOW()`.
 */
export type NewCandidate = Pick<CandidateRow, 'product_url' | 'name'> &
  Partial<Pick<CandidateRow, 'tagline'>>;

/** A row of `finds_candidate_sightings`: one platform listing. Private. */
export interface CandidateSightingRow {
  id: string;
  candidate_id: string;
  source_id: string;
  /** The platform's own id. UNIQUE with source_id, so re-pulling is idempotent. */
  external_id: string;
  /** The listing page ON the platform -- what W9 comments on, not the product site. */
  source_url: string;
  title: string | null;
  author_handle: string | null;
  posted_at: Timestamp | null;
  /** Verbatim source payload for this item. Never edited. */
  raw: Record<string, unknown>;
  seen_at: Timestamp;
}

export type NewCandidateSighting = Pick<
  CandidateSightingRow,
  'candidate_id' | 'source_id' | 'external_id' | 'source_url'
> &
  Partial<Pick<CandidateSightingRow, 'title' | 'author_handle' | 'posted_at' | 'raw'>>;

/* ========================================================================== */
/* evidence                                                                    */
/* ========================================================================== */

/** What a fetched page is to us, so scoring can ask for the pricing page. */
export type EvidencePageRole =
  | 'homepage'
  | 'pricing'
  | 'docs'
  | 'api'
  | 'mcp'
  | 'changelog'
  | 'about'
  | 'blog'
  | 'repo'
  | 'robots_txt'
  | 'llms_txt'
  | 'other';

/** Something the page asserts. The left-hand side of the C1 diff. */
export interface EvidenceClaim {
  text: string;
  /** Where on the page it was found -- selector, heading, or section. */
  locator?: string;
}

/** A verbatim excerpt. Quoted, never paraphrased, so a score is auditable. */
export interface EvidenceQuote {
  text: string;
  locator?: string;
}

/** Measured behaviour rather than text: an endpoint responded, a schema parsed. */
export interface EvidenceObservation {
  kind: string;
  detail?: string;
  value?: string | number | boolean | null;
}

/**
 * A row of `finds_evidence`. Private, immutable and append-only -- a trigger
 * refuses UPDATE, DELETE and TRUNCATE for every caller, service role included,
 * because RLS cannot stop a role that bypasses RLS. Re-crawling appends a new
 * generation under a fresh `crawl_run_id`; it never overwrites.
 */
export interface EvidenceRow {
  id: string;
  candidate_id: string;
  /** Groups one crawl pass. Verdicts record which generation they scored. */
  crawl_run_id: string;
  url: string;
  page_role: EvidencePageRole;
  /** A 404 on /docs is evidence, not a missing row. */
  http_status: number | null;
  content_type: string | null;
  content_sha256: string | null;
  fetched_at: Timestamp;
  claims: EvidenceClaim[];
  quotes: EvidenceQuote[];
  observations: EvidenceObservation[];
  created_at: Timestamp;
}

export type NewEvidence = Pick<
  EvidenceRow,
  'candidate_id' | 'crawl_run_id' | 'url' | 'page_role'
> &
  Partial<
    Pick<
      EvidenceRow,
      'http_status' | 'content_type' | 'content_sha256' | 'fetched_at' | 'claims' | 'quotes' | 'observations'
    >
  >;
